// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"net"
	"sync"

	"code.cloudfoundry.org/winc/network/netrules"
)

type NetInterface struct {
	ByNameStub        func(string) (*net.Interface, error)
	byNameMutex       sync.RWMutex
	byNameArgsForCall []struct {
		arg1 string
	}
	byNameReturns struct {
		result1 *net.Interface
		result2 error
	}
	byNameReturnsOnCall map[int]struct {
		result1 *net.Interface
		result2 error
	}
	ByIPStub        func(string) (*net.Interface, error)
	byIPMutex       sync.RWMutex
	byIPArgsForCall []struct {
		arg1 string
	}
	byIPReturns struct {
		result1 *net.Interface
		result2 error
	}
	byIPReturnsOnCall map[int]struct {
		result1 *net.Interface
		result2 error
	}
	SetMTUStub        func(string, int) error
	setMTUMutex       sync.RWMutex
	setMTUArgsForCall []struct {
		arg1 string
		arg2 int
	}
	setMTUReturns struct {
		result1 error
	}
	setMTUReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NetInterface) ByName(arg1 string) (*net.Interface, error) {
	fake.byNameMutex.Lock()
	ret, specificReturn := fake.byNameReturnsOnCall[len(fake.byNameArgsForCall)]
	fake.byNameArgsForCall = append(fake.byNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ByName", []interface{}{arg1})
	fake.byNameMutex.Unlock()
	if fake.ByNameStub != nil {
		return fake.ByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.byNameReturns.result1, fake.byNameReturns.result2
}

func (fake *NetInterface) ByNameCallCount() int {
	fake.byNameMutex.RLock()
	defer fake.byNameMutex.RUnlock()
	return len(fake.byNameArgsForCall)
}

func (fake *NetInterface) ByNameArgsForCall(i int) string {
	fake.byNameMutex.RLock()
	defer fake.byNameMutex.RUnlock()
	return fake.byNameArgsForCall[i].arg1
}

func (fake *NetInterface) ByNameReturns(result1 *net.Interface, result2 error) {
	fake.ByNameStub = nil
	fake.byNameReturns = struct {
		result1 *net.Interface
		result2 error
	}{result1, result2}
}

func (fake *NetInterface) ByNameReturnsOnCall(i int, result1 *net.Interface, result2 error) {
	fake.ByNameStub = nil
	if fake.byNameReturnsOnCall == nil {
		fake.byNameReturnsOnCall = make(map[int]struct {
			result1 *net.Interface
			result2 error
		})
	}
	fake.byNameReturnsOnCall[i] = struct {
		result1 *net.Interface
		result2 error
	}{result1, result2}
}

func (fake *NetInterface) ByIP(arg1 string) (*net.Interface, error) {
	fake.byIPMutex.Lock()
	ret, specificReturn := fake.byIPReturnsOnCall[len(fake.byIPArgsForCall)]
	fake.byIPArgsForCall = append(fake.byIPArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ByIP", []interface{}{arg1})
	fake.byIPMutex.Unlock()
	if fake.ByIPStub != nil {
		return fake.ByIPStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.byIPReturns.result1, fake.byIPReturns.result2
}

func (fake *NetInterface) ByIPCallCount() int {
	fake.byIPMutex.RLock()
	defer fake.byIPMutex.RUnlock()
	return len(fake.byIPArgsForCall)
}

func (fake *NetInterface) ByIPArgsForCall(i int) string {
	fake.byIPMutex.RLock()
	defer fake.byIPMutex.RUnlock()
	return fake.byIPArgsForCall[i].arg1
}

func (fake *NetInterface) ByIPReturns(result1 *net.Interface, result2 error) {
	fake.ByIPStub = nil
	fake.byIPReturns = struct {
		result1 *net.Interface
		result2 error
	}{result1, result2}
}

func (fake *NetInterface) ByIPReturnsOnCall(i int, result1 *net.Interface, result2 error) {
	fake.ByIPStub = nil
	if fake.byIPReturnsOnCall == nil {
		fake.byIPReturnsOnCall = make(map[int]struct {
			result1 *net.Interface
			result2 error
		})
	}
	fake.byIPReturnsOnCall[i] = struct {
		result1 *net.Interface
		result2 error
	}{result1, result2}
}

func (fake *NetInterface) SetMTU(arg1 string, arg2 int) error {
	fake.setMTUMutex.Lock()
	ret, specificReturn := fake.setMTUReturnsOnCall[len(fake.setMTUArgsForCall)]
	fake.setMTUArgsForCall = append(fake.setMTUArgsForCall, struct {
		arg1 string
		arg2 int
	}{arg1, arg2})
	fake.recordInvocation("SetMTU", []interface{}{arg1, arg2})
	fake.setMTUMutex.Unlock()
	if fake.SetMTUStub != nil {
		return fake.SetMTUStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.setMTUReturns.result1
}

func (fake *NetInterface) SetMTUCallCount() int {
	fake.setMTUMutex.RLock()
	defer fake.setMTUMutex.RUnlock()
	return len(fake.setMTUArgsForCall)
}

func (fake *NetInterface) SetMTUArgsForCall(i int) (string, int) {
	fake.setMTUMutex.RLock()
	defer fake.setMTUMutex.RUnlock()
	return fake.setMTUArgsForCall[i].arg1, fake.setMTUArgsForCall[i].arg2
}

func (fake *NetInterface) SetMTUReturns(result1 error) {
	fake.SetMTUStub = nil
	fake.setMTUReturns = struct {
		result1 error
	}{result1}
}

func (fake *NetInterface) SetMTUReturnsOnCall(i int, result1 error) {
	fake.SetMTUStub = nil
	if fake.setMTUReturnsOnCall == nil {
		fake.setMTUReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setMTUReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *NetInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.byNameMutex.RLock()
	defer fake.byNameMutex.RUnlock()
	fake.byIPMutex.RLock()
	defer fake.byIPMutex.RUnlock()
	fake.setMTUMutex.RLock()
	defer fake.setMTUMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NetInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ netrules.NetInterface = new(NetInterface)
