// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/winc/hcs"
	"code.cloudfoundry.org/winc/runtime"
	"code.cloudfoundry.org/winc/runtime/container"
	specs "github.com/opencontainers/runtime-spec/specs-go"
)

type ContainerManager struct {
	CreateStub        func(*specs.Spec, string) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 *specs.Spec
		arg2 string
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	CredentialSpecFromEnvStub        func([]string, string, string, string, string) (string, error)
	credentialSpecFromEnvMutex       sync.RWMutex
	credentialSpecFromEnvArgsForCall []struct {
		arg1 []string
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	credentialSpecFromEnvReturns struct {
		result1 string
		result2 error
	}
	credentialSpecFromEnvReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	CredentialSpecFromFileStub        func(string) (string, error)
	credentialSpecFromFileMutex       sync.RWMutex
	credentialSpecFromFileArgsForCall []struct {
		arg1 string
	}
	credentialSpecFromFileReturns struct {
		result1 string
		result2 error
	}
	credentialSpecFromFileReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DeleteStub        func(bool) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 bool
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	ExecStub        func(*specs.Process, bool) (hcs.Process, error)
	execMutex       sync.RWMutex
	execArgsForCall []struct {
		arg1 *specs.Process
		arg2 bool
	}
	execReturns struct {
		result1 hcs.Process
		result2 error
	}
	execReturnsOnCall map[int]struct {
		result1 hcs.Process
		result2 error
	}
	SpecStub        func(string) (*specs.Spec, error)
	specMutex       sync.RWMutex
	specArgsForCall []struct {
		arg1 string
	}
	specReturns struct {
		result1 *specs.Spec
		result2 error
	}
	specReturnsOnCall map[int]struct {
		result1 *specs.Spec
		result2 error
	}
	StatsStub        func() (container.Statistics, error)
	statsMutex       sync.RWMutex
	statsArgsForCall []struct {
	}
	statsReturns struct {
		result1 container.Statistics
		result2 error
	}
	statsReturnsOnCall map[int]struct {
		result1 container.Statistics
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ContainerManager) Create(arg1 *specs.Spec, arg2 string) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 *specs.Spec
		arg2 string
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ContainerManager) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *ContainerManager) CreateCalls(stub func(*specs.Spec, string) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *ContainerManager) CreateArgsForCall(i int) (*specs.Spec, string) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ContainerManager) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *ContainerManager) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ContainerManager) CredentialSpecFromEnv(arg1 []string, arg2 string, arg3 string, arg4 string, arg5 string) (string, error) {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.credentialSpecFromEnvMutex.Lock()
	ret, specificReturn := fake.credentialSpecFromEnvReturnsOnCall[len(fake.credentialSpecFromEnvArgsForCall)]
	fake.credentialSpecFromEnvArgsForCall = append(fake.credentialSpecFromEnvArgsForCall, struct {
		arg1 []string
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1Copy, arg2, arg3, arg4, arg5})
	stub := fake.CredentialSpecFromEnvStub
	fakeReturns := fake.credentialSpecFromEnvReturns
	fake.recordInvocation("CredentialSpecFromEnv", []interface{}{arg1Copy, arg2, arg3, arg4, arg5})
	fake.credentialSpecFromEnvMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ContainerManager) CredentialSpecFromEnvCallCount() int {
	fake.credentialSpecFromEnvMutex.RLock()
	defer fake.credentialSpecFromEnvMutex.RUnlock()
	return len(fake.credentialSpecFromEnvArgsForCall)
}

func (fake *ContainerManager) CredentialSpecFromEnvCalls(stub func([]string, string, string, string, string) (string, error)) {
	fake.credentialSpecFromEnvMutex.Lock()
	defer fake.credentialSpecFromEnvMutex.Unlock()
	fake.CredentialSpecFromEnvStub = stub
}

func (fake *ContainerManager) CredentialSpecFromEnvArgsForCall(i int) ([]string, string, string, string, string) {
	fake.credentialSpecFromEnvMutex.RLock()
	defer fake.credentialSpecFromEnvMutex.RUnlock()
	argsForCall := fake.credentialSpecFromEnvArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *ContainerManager) CredentialSpecFromEnvReturns(result1 string, result2 error) {
	fake.credentialSpecFromEnvMutex.Lock()
	defer fake.credentialSpecFromEnvMutex.Unlock()
	fake.CredentialSpecFromEnvStub = nil
	fake.credentialSpecFromEnvReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) CredentialSpecFromEnvReturnsOnCall(i int, result1 string, result2 error) {
	fake.credentialSpecFromEnvMutex.Lock()
	defer fake.credentialSpecFromEnvMutex.Unlock()
	fake.CredentialSpecFromEnvStub = nil
	if fake.credentialSpecFromEnvReturnsOnCall == nil {
		fake.credentialSpecFromEnvReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.credentialSpecFromEnvReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) CredentialSpecFromFile(arg1 string) (string, error) {
	fake.credentialSpecFromFileMutex.Lock()
	ret, specificReturn := fake.credentialSpecFromFileReturnsOnCall[len(fake.credentialSpecFromFileArgsForCall)]
	fake.credentialSpecFromFileArgsForCall = append(fake.credentialSpecFromFileArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CredentialSpecFromFileStub
	fakeReturns := fake.credentialSpecFromFileReturns
	fake.recordInvocation("CredentialSpecFromFile", []interface{}{arg1})
	fake.credentialSpecFromFileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ContainerManager) CredentialSpecFromFileCallCount() int {
	fake.credentialSpecFromFileMutex.RLock()
	defer fake.credentialSpecFromFileMutex.RUnlock()
	return len(fake.credentialSpecFromFileArgsForCall)
}

func (fake *ContainerManager) CredentialSpecFromFileCalls(stub func(string) (string, error)) {
	fake.credentialSpecFromFileMutex.Lock()
	defer fake.credentialSpecFromFileMutex.Unlock()
	fake.CredentialSpecFromFileStub = stub
}

func (fake *ContainerManager) CredentialSpecFromFileArgsForCall(i int) string {
	fake.credentialSpecFromFileMutex.RLock()
	defer fake.credentialSpecFromFileMutex.RUnlock()
	argsForCall := fake.credentialSpecFromFileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ContainerManager) CredentialSpecFromFileReturns(result1 string, result2 error) {
	fake.credentialSpecFromFileMutex.Lock()
	defer fake.credentialSpecFromFileMutex.Unlock()
	fake.CredentialSpecFromFileStub = nil
	fake.credentialSpecFromFileReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) CredentialSpecFromFileReturnsOnCall(i int, result1 string, result2 error) {
	fake.credentialSpecFromFileMutex.Lock()
	defer fake.credentialSpecFromFileMutex.Unlock()
	fake.CredentialSpecFromFileStub = nil
	if fake.credentialSpecFromFileReturnsOnCall == nil {
		fake.credentialSpecFromFileReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.credentialSpecFromFileReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) Delete(arg1 bool) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 bool
	}{arg1})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ContainerManager) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *ContainerManager) DeleteCalls(stub func(bool) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *ContainerManager) DeleteArgsForCall(i int) bool {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ContainerManager) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *ContainerManager) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ContainerManager) Exec(arg1 *specs.Process, arg2 bool) (hcs.Process, error) {
	fake.execMutex.Lock()
	ret, specificReturn := fake.execReturnsOnCall[len(fake.execArgsForCall)]
	fake.execArgsForCall = append(fake.execArgsForCall, struct {
		arg1 *specs.Process
		arg2 bool
	}{arg1, arg2})
	stub := fake.ExecStub
	fakeReturns := fake.execReturns
	fake.recordInvocation("Exec", []interface{}{arg1, arg2})
	fake.execMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ContainerManager) ExecCallCount() int {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	return len(fake.execArgsForCall)
}

func (fake *ContainerManager) ExecCalls(stub func(*specs.Process, bool) (hcs.Process, error)) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = stub
}

func (fake *ContainerManager) ExecArgsForCall(i int) (*specs.Process, bool) {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	argsForCall := fake.execArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ContainerManager) ExecReturns(result1 hcs.Process, result2 error) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = nil
	fake.execReturns = struct {
		result1 hcs.Process
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) ExecReturnsOnCall(i int, result1 hcs.Process, result2 error) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = nil
	if fake.execReturnsOnCall == nil {
		fake.execReturnsOnCall = make(map[int]struct {
			result1 hcs.Process
			result2 error
		})
	}
	fake.execReturnsOnCall[i] = struct {
		result1 hcs.Process
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) Spec(arg1 string) (*specs.Spec, error) {
	fake.specMutex.Lock()
	ret, specificReturn := fake.specReturnsOnCall[len(fake.specArgsForCall)]
	fake.specArgsForCall = append(fake.specArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SpecStub
	fakeReturns := fake.specReturns
	fake.recordInvocation("Spec", []interface{}{arg1})
	fake.specMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ContainerManager) SpecCallCount() int {
	fake.specMutex.RLock()
	defer fake.specMutex.RUnlock()
	return len(fake.specArgsForCall)
}

func (fake *ContainerManager) SpecCalls(stub func(string) (*specs.Spec, error)) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = stub
}

func (fake *ContainerManager) SpecArgsForCall(i int) string {
	fake.specMutex.RLock()
	defer fake.specMutex.RUnlock()
	argsForCall := fake.specArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ContainerManager) SpecReturns(result1 *specs.Spec, result2 error) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = nil
	fake.specReturns = struct {
		result1 *specs.Spec
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) SpecReturnsOnCall(i int, result1 *specs.Spec, result2 error) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = nil
	if fake.specReturnsOnCall == nil {
		fake.specReturnsOnCall = make(map[int]struct {
			result1 *specs.Spec
			result2 error
		})
	}
	fake.specReturnsOnCall[i] = struct {
		result1 *specs.Spec
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) Stats() (container.Statistics, error) {
	fake.statsMutex.Lock()
	ret, specificReturn := fake.statsReturnsOnCall[len(fake.statsArgsForCall)]
	fake.statsArgsForCall = append(fake.statsArgsForCall, struct {
	}{})
	stub := fake.StatsStub
	fakeReturns := fake.statsReturns
	fake.recordInvocation("Stats", []interface{}{})
	fake.statsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ContainerManager) StatsCallCount() int {
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	return len(fake.statsArgsForCall)
}

func (fake *ContainerManager) StatsCalls(stub func() (container.Statistics, error)) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = stub
}

func (fake *ContainerManager) StatsReturns(result1 container.Statistics, result2 error) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = nil
	fake.statsReturns = struct {
		result1 container.Statistics
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) StatsReturnsOnCall(i int, result1 container.Statistics, result2 error) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = nil
	if fake.statsReturnsOnCall == nil {
		fake.statsReturnsOnCall = make(map[int]struct {
			result1 container.Statistics
			result2 error
		})
	}
	fake.statsReturnsOnCall[i] = struct {
		result1 container.Statistics
		result2 error
	}{result1, result2}
}

func (fake *ContainerManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.credentialSpecFromEnvMutex.RLock()
	defer fake.credentialSpecFromEnvMutex.RUnlock()
	fake.credentialSpecFromFileMutex.RLock()
	defer fake.credentialSpecFromFileMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	fake.specMutex.RLock()
	defer fake.specMutex.RUnlock()
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ContainerManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ runtime.ContainerManager = new(ContainerManager)
