// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/winc/runtime"
	"github.com/Microsoft/hcsshim"
)

type HCSQuery struct {
	GetContainersStub        func(hcsshim.ComputeSystemQuery) ([]hcsshim.ContainerProperties, error)
	getContainersMutex       sync.RWMutex
	getContainersArgsForCall []struct {
		arg1 hcsshim.ComputeSystemQuery
	}
	getContainersReturns struct {
		result1 []hcsshim.ContainerProperties
		result2 error
	}
	getContainersReturnsOnCall map[int]struct {
		result1 []hcsshim.ContainerProperties
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *HCSQuery) GetContainers(arg1 hcsshim.ComputeSystemQuery) ([]hcsshim.ContainerProperties, error) {
	fake.getContainersMutex.Lock()
	ret, specificReturn := fake.getContainersReturnsOnCall[len(fake.getContainersArgsForCall)]
	fake.getContainersArgsForCall = append(fake.getContainersArgsForCall, struct {
		arg1 hcsshim.ComputeSystemQuery
	}{arg1})
	fake.recordInvocation("GetContainers", []interface{}{arg1})
	fake.getContainersMutex.Unlock()
	if fake.GetContainersStub != nil {
		return fake.GetContainersStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getContainersReturns.result1, fake.getContainersReturns.result2
}

func (fake *HCSQuery) GetContainersCallCount() int {
	fake.getContainersMutex.RLock()
	defer fake.getContainersMutex.RUnlock()
	return len(fake.getContainersArgsForCall)
}

func (fake *HCSQuery) GetContainersArgsForCall(i int) hcsshim.ComputeSystemQuery {
	fake.getContainersMutex.RLock()
	defer fake.getContainersMutex.RUnlock()
	return fake.getContainersArgsForCall[i].arg1
}

func (fake *HCSQuery) GetContainersReturns(result1 []hcsshim.ContainerProperties, result2 error) {
	fake.GetContainersStub = nil
	fake.getContainersReturns = struct {
		result1 []hcsshim.ContainerProperties
		result2 error
	}{result1, result2}
}

func (fake *HCSQuery) GetContainersReturnsOnCall(i int, result1 []hcsshim.ContainerProperties, result2 error) {
	fake.GetContainersStub = nil
	if fake.getContainersReturnsOnCall == nil {
		fake.getContainersReturnsOnCall = make(map[int]struct {
			result1 []hcsshim.ContainerProperties
			result2 error
		})
	}
	fake.getContainersReturnsOnCall[i] = struct {
		result1 []hcsshim.ContainerProperties
		result2 error
	}{result1, result2}
}

func (fake *HCSQuery) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getContainersMutex.RLock()
	defer fake.getContainersMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *HCSQuery) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ runtime.HCSQuery = new(HCSQuery)
