// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/winc/hcs"
	"code.cloudfoundry.org/winc/runtime"
	"code.cloudfoundry.org/winc/runtime/winsyscall"
	"github.com/sirupsen/logrus"
)

type StateFactory struct {
	NewManagerStub        func(*logrus.Entry, *hcs.Client, *winsyscall.WinSyscall, string, string) runtime.StateManager
	newManagerMutex       sync.RWMutex
	newManagerArgsForCall []struct {
		arg1 *logrus.Entry
		arg2 *hcs.Client
		arg3 *winsyscall.WinSyscall
		arg4 string
		arg5 string
	}
	newManagerReturns struct {
		result1 runtime.StateManager
	}
	newManagerReturnsOnCall map[int]struct {
		result1 runtime.StateManager
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *StateFactory) NewManager(arg1 *logrus.Entry, arg2 *hcs.Client, arg3 *winsyscall.WinSyscall, arg4 string, arg5 string) runtime.StateManager {
	fake.newManagerMutex.Lock()
	ret, specificReturn := fake.newManagerReturnsOnCall[len(fake.newManagerArgsForCall)]
	fake.newManagerArgsForCall = append(fake.newManagerArgsForCall, struct {
		arg1 *logrus.Entry
		arg2 *hcs.Client
		arg3 *winsyscall.WinSyscall
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	fake.recordInvocation("NewManager", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.newManagerMutex.Unlock()
	if fake.NewManagerStub != nil {
		return fake.NewManagerStub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.newManagerReturns.result1
}

func (fake *StateFactory) NewManagerCallCount() int {
	fake.newManagerMutex.RLock()
	defer fake.newManagerMutex.RUnlock()
	return len(fake.newManagerArgsForCall)
}

func (fake *StateFactory) NewManagerArgsForCall(i int) (*logrus.Entry, *hcs.Client, *winsyscall.WinSyscall, string, string) {
	fake.newManagerMutex.RLock()
	defer fake.newManagerMutex.RUnlock()
	return fake.newManagerArgsForCall[i].arg1, fake.newManagerArgsForCall[i].arg2, fake.newManagerArgsForCall[i].arg3, fake.newManagerArgsForCall[i].arg4, fake.newManagerArgsForCall[i].arg5
}

func (fake *StateFactory) NewManagerReturns(result1 runtime.StateManager) {
	fake.NewManagerStub = nil
	fake.newManagerReturns = struct {
		result1 runtime.StateManager
	}{result1}
}

func (fake *StateFactory) NewManagerReturnsOnCall(i int, result1 runtime.StateManager) {
	fake.NewManagerStub = nil
	if fake.newManagerReturnsOnCall == nil {
		fake.newManagerReturnsOnCall = make(map[int]struct {
			result1 runtime.StateManager
		})
	}
	fake.newManagerReturnsOnCall[i] = struct {
		result1 runtime.StateManager
	}{result1}
}

func (fake *StateFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newManagerMutex.RLock()
	defer fake.newManagerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *StateFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ runtime.StateFactory = new(StateFactory)
