// Code generated by counterfeiter. DO NOT EDIT.
package sandboxfakes

import (
	"sync"

	"code.cloudfoundry.org/winc/sandbox"
	"github.com/Microsoft/hcsshim"
)

type FakeHCSClient struct {
	CreateLayerStub        func(hcsshim.DriverInfo, string, string, []string) (string, error)
	createLayerMutex       sync.RWMutex
	createLayerArgsForCall []struct {
		arg1 hcsshim.DriverInfo
		arg2 string
		arg3 string
		arg4 []string
	}
	createLayerReturns struct {
		result1 string
		result2 error
	}
	createLayerReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	LayerExistsStub        func(hcsshim.DriverInfo, string) (bool, error)
	layerExistsMutex       sync.RWMutex
	layerExistsArgsForCall []struct {
		arg1 hcsshim.DriverInfo
		arg2 string
	}
	layerExistsReturns struct {
		result1 bool
		result2 error
	}
	layerExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	DestroyLayerStub        func(hcsshim.DriverInfo, string) error
	destroyLayerMutex       sync.RWMutex
	destroyLayerArgsForCall []struct {
		arg1 hcsshim.DriverInfo
		arg2 string
	}
	destroyLayerReturns struct {
		result1 error
	}
	destroyLayerReturnsOnCall map[int]struct {
		result1 error
	}
	RetryableStub        func(error) bool
	retryableMutex       sync.RWMutex
	retryableArgsForCall []struct {
		arg1 error
	}
	retryableReturns struct {
		result1 bool
	}
	retryableReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHCSClient) CreateLayer(arg1 hcsshim.DriverInfo, arg2 string, arg3 string, arg4 []string) (string, error) {
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.createLayerMutex.Lock()
	ret, specificReturn := fake.createLayerReturnsOnCall[len(fake.createLayerArgsForCall)]
	fake.createLayerArgsForCall = append(fake.createLayerArgsForCall, struct {
		arg1 hcsshim.DriverInfo
		arg2 string
		arg3 string
		arg4 []string
	}{arg1, arg2, arg3, arg4Copy})
	fake.recordInvocation("CreateLayer", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.createLayerMutex.Unlock()
	if fake.CreateLayerStub != nil {
		return fake.CreateLayerStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createLayerReturns.result1, fake.createLayerReturns.result2
}

func (fake *FakeHCSClient) CreateLayerCallCount() int {
	fake.createLayerMutex.RLock()
	defer fake.createLayerMutex.RUnlock()
	return len(fake.createLayerArgsForCall)
}

func (fake *FakeHCSClient) CreateLayerArgsForCall(i int) (hcsshim.DriverInfo, string, string, []string) {
	fake.createLayerMutex.RLock()
	defer fake.createLayerMutex.RUnlock()
	return fake.createLayerArgsForCall[i].arg1, fake.createLayerArgsForCall[i].arg2, fake.createLayerArgsForCall[i].arg3, fake.createLayerArgsForCall[i].arg4
}

func (fake *FakeHCSClient) CreateLayerReturns(result1 string, result2 error) {
	fake.CreateLayerStub = nil
	fake.createLayerReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeHCSClient) CreateLayerReturnsOnCall(i int, result1 string, result2 error) {
	fake.CreateLayerStub = nil
	if fake.createLayerReturnsOnCall == nil {
		fake.createLayerReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createLayerReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeHCSClient) LayerExists(arg1 hcsshim.DriverInfo, arg2 string) (bool, error) {
	fake.layerExistsMutex.Lock()
	ret, specificReturn := fake.layerExistsReturnsOnCall[len(fake.layerExistsArgsForCall)]
	fake.layerExistsArgsForCall = append(fake.layerExistsArgsForCall, struct {
		arg1 hcsshim.DriverInfo
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("LayerExists", []interface{}{arg1, arg2})
	fake.layerExistsMutex.Unlock()
	if fake.LayerExistsStub != nil {
		return fake.LayerExistsStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.layerExistsReturns.result1, fake.layerExistsReturns.result2
}

func (fake *FakeHCSClient) LayerExistsCallCount() int {
	fake.layerExistsMutex.RLock()
	defer fake.layerExistsMutex.RUnlock()
	return len(fake.layerExistsArgsForCall)
}

func (fake *FakeHCSClient) LayerExistsArgsForCall(i int) (hcsshim.DriverInfo, string) {
	fake.layerExistsMutex.RLock()
	defer fake.layerExistsMutex.RUnlock()
	return fake.layerExistsArgsForCall[i].arg1, fake.layerExistsArgsForCall[i].arg2
}

func (fake *FakeHCSClient) LayerExistsReturns(result1 bool, result2 error) {
	fake.LayerExistsStub = nil
	fake.layerExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeHCSClient) LayerExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.LayerExistsStub = nil
	if fake.layerExistsReturnsOnCall == nil {
		fake.layerExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.layerExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeHCSClient) DestroyLayer(arg1 hcsshim.DriverInfo, arg2 string) error {
	fake.destroyLayerMutex.Lock()
	ret, specificReturn := fake.destroyLayerReturnsOnCall[len(fake.destroyLayerArgsForCall)]
	fake.destroyLayerArgsForCall = append(fake.destroyLayerArgsForCall, struct {
		arg1 hcsshim.DriverInfo
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("DestroyLayer", []interface{}{arg1, arg2})
	fake.destroyLayerMutex.Unlock()
	if fake.DestroyLayerStub != nil {
		return fake.DestroyLayerStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.destroyLayerReturns.result1
}

func (fake *FakeHCSClient) DestroyLayerCallCount() int {
	fake.destroyLayerMutex.RLock()
	defer fake.destroyLayerMutex.RUnlock()
	return len(fake.destroyLayerArgsForCall)
}

func (fake *FakeHCSClient) DestroyLayerArgsForCall(i int) (hcsshim.DriverInfo, string) {
	fake.destroyLayerMutex.RLock()
	defer fake.destroyLayerMutex.RUnlock()
	return fake.destroyLayerArgsForCall[i].arg1, fake.destroyLayerArgsForCall[i].arg2
}

func (fake *FakeHCSClient) DestroyLayerReturns(result1 error) {
	fake.DestroyLayerStub = nil
	fake.destroyLayerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeHCSClient) DestroyLayerReturnsOnCall(i int, result1 error) {
	fake.DestroyLayerStub = nil
	if fake.destroyLayerReturnsOnCall == nil {
		fake.destroyLayerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.destroyLayerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeHCSClient) Retryable(arg1 error) bool {
	fake.retryableMutex.Lock()
	ret, specificReturn := fake.retryableReturnsOnCall[len(fake.retryableArgsForCall)]
	fake.retryableArgsForCall = append(fake.retryableArgsForCall, struct {
		arg1 error
	}{arg1})
	fake.recordInvocation("Retryable", []interface{}{arg1})
	fake.retryableMutex.Unlock()
	if fake.RetryableStub != nil {
		return fake.RetryableStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.retryableReturns.result1
}

func (fake *FakeHCSClient) RetryableCallCount() int {
	fake.retryableMutex.RLock()
	defer fake.retryableMutex.RUnlock()
	return len(fake.retryableArgsForCall)
}

func (fake *FakeHCSClient) RetryableArgsForCall(i int) error {
	fake.retryableMutex.RLock()
	defer fake.retryableMutex.RUnlock()
	return fake.retryableArgsForCall[i].arg1
}

func (fake *FakeHCSClient) RetryableReturns(result1 bool) {
	fake.RetryableStub = nil
	fake.retryableReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeHCSClient) RetryableReturnsOnCall(i int, result1 bool) {
	fake.RetryableStub = nil
	if fake.retryableReturnsOnCall == nil {
		fake.retryableReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.retryableReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeHCSClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createLayerMutex.RLock()
	defer fake.createLayerMutex.RUnlock()
	fake.layerExistsMutex.RLock()
	defer fake.layerExistsMutex.RUnlock()
	fake.destroyLayerMutex.RLock()
	defer fake.destroyLayerMutex.RUnlock()
	fake.retryableMutex.RLock()
	defer fake.retryableMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHCSClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sandbox.HCSClient = new(FakeHCSClient)
